AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Second Brain System - Telegram Bot + AWS Lambda + DynamoDB + AI Processing

Globals:
  Function:
    Timeout: 30
    Runtime: python3.12
    MemorySize: 256
    Environment:
      Variables:
        DDB_TABLE_NAME: !Ref SecondBrainTable
        LOG_LEVEL: INFO

Parameters:
  AnthropicApiKey:
    Type: String
    Description: Anthropic API key for Claude AI processing
    NoEcho: true
  OpenaiApiKey:
    Type: String
    Description: OpenAI API key (fallback if Anthropic fails)
    NoEcho: true
  TelegramBotToken:
    Type: String
    Description: Telegram bot token from BotFather
    NoEcho: true
  TelegramSecretToken:
    Type: String
    Description: Secret token for webhook verification
    NoEcho: true
  UserChatId:
    Type: String
    Description: Your personal Telegram chat ID for digest messages
    NoEcho: true

Resources:
  SecondBrainTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SecondBrain
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: category
          AttributeType: S
        - AttributeName: expires_at
          AttributeType: N
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: StatusIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: category
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: expires_at
        Enabled: true

  ProcessorLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SecondBrainProcessor
      CodeUri: processor/
      Handler: app.lambda_handler
      Environment:
        Variables:
          ANTHROPIC_API_KEY: !Ref AnthropicApiKey
          OPENAI_API_KEY: !Ref OpenaiApiKey
          TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
          TELEGRAM_SECRET_TOKEN: !Ref TelegramSecretToken
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SecondBrainTable
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED

  DigestLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SecondBrainDigest
      CodeUri: digest/
      Handler: app.lambda_handler
      Environment:
        Variables:
          ANTHROPIC_API_KEY: !Ref AnthropicApiKey
          OPENAI_API_KEY: !Ref OpenaiApiKey
          TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
          USER_CHAT_ID: !Ref UserChatId
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref SecondBrainTable

  DailyDigestRule:
    Type: AWS::Events::Rule
    Properties:
      Name: SecondBrainDailyDigest
      Description: Trigger daily digest at 8AM UTC
      ScheduleExpression: cron(0 8 * * ? *)
      State: ENABLED
      Targets:
        - Arn: !GetAtt DigestLambda.Arn
          Id: DailyDigestTarget

  WeeklyDigestRule:
    Type: AWS::Events::Rule
    Properties:
      Name: SecondBrainWeeklyDigest
      Description: Trigger weekly digest on Sundays at 9AM UTC
      ScheduleExpression: cron(0 9 ? * SUN *)
      State: ENABLED
      Targets:
        - Arn: !GetAtt DigestLambda.Arn
          Id: WeeklyDigestTarget

  PermissionForEventsToInvokeDigest:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DigestLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt DailyDigestRule.Arn

  PermissionForWeeklyEventsToInvokeDigest:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DigestLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt WeeklyDigestRule.Arn

Outputs:
  ProcessorLambdaUrl:
    Description: URL for Telegram webhook
    Value: !GetAtt ProcessorLambdaUrl.FunctionUrl
  SecondBrainTableName:
    Description: DynamoDB table name
    Value: !Ref SecondBrainTable
  ProcessorFunctionName:
    Description: Processor Lambda function name
    Value: !Ref ProcessorLambda
  DigestFunctionName:
    Description: Digest Lambda function name
    Value: !Ref DigestLambda